# -*- coding: utf-8 -*-
"""Análisis de felicidad

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TR6CRsmDL0w5irwbnj-GT30uTBwtYYjj
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

# Configuración visual
sns.set(style="whitegrid")
plt.rcParams["figure.figsize"] = (10,6)

# Cargar el dataset
df = pd.read_csv('2016.csv')

# Vista general
df.head()

# Verificar valores faltantes
df.isnull().sum()

# Rellenar valores faltantes con la media de cada columna numérica
numeric_cols = df.select_dtypes(include=np.number).columns
df[numeric_cols] = df[numeric_cols].fillna(df[numeric_cols].mean())

# Confirmar limpieza
df.isnull().sum()

from sklearn.preprocessing import StandardScaler

# Top 10 países por Happiness Score
top10 = df.sort_values(by='Happiness Score', ascending=False).head(10)

# Seleccionar columnas a escalar
scaler = StandardScaler()
scaled_values = scaler.fit_transform(
    top10[['Economy (GDP per Capita)', 'Health (Life Expectancy)']]
)

top10_scaled = top10[['Country']].copy()
top10_scaled['GDP per Capita (estandarizado)'] = scaled_values[:, 0]
top10_scaled['Esperanza de Vida (estandarizada)'] = scaled_values[:, 1]

# Reestructurar para graficar
top10_melted = top10_scaled.melt(
    id_vars='Country',
    var_name='Indicador',
    value_name='Valor'
)

sns.barplot(data=top10_melted, x='Country', y='Valor', hue='Indicador')
plt.xticks(rotation=45)
plt.title('Top 10 países ')
plt.show()

variables = [
    'Economy (GDP per Capita)',
    'Family',
    'Health (Life Expectancy)',
    'Freedom',
    'Trust (Government Corruption)',
    'Generosity',
    'Happiness Score'
]

# Reemplazar espacios vacíos por NaN
df[variables] = df[variables].replace(' ', np.nan)

# Convertir explícitamente a numérico
for col in variables:
    df[col] = pd.to_numeric(df[col], errors='coerce')

# Rellenar NaN con la media
df[variables] = df[variables].fillna(df[variables].mean())

corr = df[variables].corr()

plt.figure(figsize=(10,8))
sns.heatmap(corr, annot=True, cmap='coolwarm')
plt.title('Matriz de correlación entre variables')
plt.show()

plt.figure(figsize=(10,6))
sns.scatterplot(
    data=df,
    x='Economy (GDP per Capita)',
    y='Happiness Score',
    hue='Region'
)
plt.title('Relación entre GDP per Capita y Happiness Score por Región')
plt.show()

region_happiness = df.groupby('Region')['Happiness Score'].mean().reset_index()

plt.pie(
    region_happiness['Happiness Score'],
    labels=region_happiness['Region'],
    autopct='%1.1f%%',
    startangle=140
)
plt.title('Distribución del Happiness Score por Región')
plt.show()

fig = px.choropleth(
    df,
    locations='Country',
    locationmode='country names',
    color='Economy (GDP per Capita)',
    hover_name='Country',
    hover_data=['Health (Life Expectancy)'],
    color_continuous_scale='Viridis',
    title='GDP per Capita por país con Esperanza de Vida Saludable'
)

fig.show()

fig = px.scatter(
    df,
    x='Economy (GDP per Capita)',
    y='Happiness Score',
    color='Region',
    size='Health (Life Expectancy)',
    hover_name='Country',
    title='Dashboard: GDP, Felicidad, Salud y Región'
)

fig.show()

"""Este dashboard analiza los factores que influyen en el nivel de felicidad de los países a partir del World Happiness Report 2016.
En primer lugar, observamos que los países con mayor Happiness Score también presentan altos niveles de PIB per cápita y esperanza de vida saludable, lo cual sugiere una fuerte relación entre bienestar económico, salud y felicidad.
El análisis de correlación muestra que el GDP per Capita, la familia y la salud tienen una correlación positiva significativa con el Happiness Score, mientras que factores como la corrupción tienen una relación negativa.
El gráfico de dispersión evidencia que, en todas las regiones, un mayor ingreso per cápita tiende a asociarse con mayores niveles de felicidad, aunque existen diferencias regionales importantes.
La visualización por regiones indica que Europa Occidental y América del Norte concentran los mayores niveles promedio de felicidad.
Finalmente, el mapa interactivo permite identificar geográficamente cómo el desarrollo económico y la esperanza de vida saludable varían entre países, reforzando la importancia de políticas públicas orientadas al bienestar integral de la población.
"""